<?php

namespace anandPackages\contact\Http\Controllers;


use anandPackages\contact\Mail\contactMailable;
use anandPackages\contact\Models\contactModel;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class Contactuscontroller extends Controller
{
    //
    public function index(){
        return view('contact::contact');
    }
    public function sendTo(Request $request)
    {
        contactModel::create($request->all());
        Mail::to(config('contact.send_email_to'))->send(new contactMailable($request->message));
        return  redirect('contact');// TODO: Change the autogenerated stub
    }
}
